# Generated by Django 5.2.1 on 2025-05-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="books",
            fields=[
                (
                    "isbn",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name=13
                    ),
                ),
                ("title", models.TextField()),
                ("genre", models.TextField()),
                ("author", models.TextField()),
                ("summary", models.TextField()),
                ("publisher", models.TextField()),
                ("language", models.TextField()),
                ("edition", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                ("userId", models.TextField(primary_key=True, serialize=False)),
                ("firstName", models.TextField()),
                ("lastName", models.TextField()),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="bookInstances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchaseDate", models.DateTimeField()),
                (
                    "isbn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_management_app.books",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="logins",
            fields=[
                ("username", models.TextField(primary_key=True, serialize=False)),
                ("password", models.TextField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_management_app.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="borrows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dueDate", models.DateTimeField()),
                ("returnedDate", models.DateTimeField()),
                ("fine", models.FloatField()),
                (
                    "isbn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="library_management_app.books",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="library_management_app.users",
                    ),
                ),
            ],
        ),
    ]
