# Generated by Django 5.2.1 on 2025-05-20 10:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('isbn', models.BigIntegerField(primary_key=True, serialize=False, verbose_name=13)),
                ('title', models.TextField()),
                ('genre', models.TextField()),
                ('author', models.TextField()),
                ('summary', models.TextField()),
                ('publisher', models.TextField()),
                ('language', models.TextField()),
                ('edition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='bookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_management_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_management_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField()),
                ('fine', models.FloatField()),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_management_app.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_management_app.user')),
            ],
        ),
    ]
