# Generated by Django 5.2.1 on 2025-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=None),
        ),
    ]
