# Generated by Django 5.2.1 on 2025-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='returned_date',
            field=models.DateField(),
        ),
    ]
