# Generated by Django 5.2.1 on 2025-05-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0002_users_createdat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
        migrations.RenameModel(
            old_name='bookInstances',
            new_name='bookInstance',
        ),
        migrations.RenameModel(
            old_name='borrows',
            new_name='borrow',
        ),
        migrations.RenameModel(
            old_name='logins',
            new_name='login',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
