# Generated by Django 5.2.1 on 2025-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0004_alter_borrow_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='fine',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='returned_date',
            field=models.DateField(null=True),
        ),
    ]
