# Generated by Django 5.2.1 on 2025-05-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0006_genres_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(null=True),
        ),
    ]
