# Generated by Django 5.2.1 on 2025-05-28 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0007_alter_genres_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='copy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_management_app.bookinstance'),
        ),
    ]
