# Generated by Django 5.2.1 on 2025-05-28 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0008_borrow_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_management_app.bookinstance'),
        ),
    ]
