# Generated by Django 5.2.1 on 2025-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0011_bookinstance_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
